# Generated by Django 4.0.1 on 2022-04-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField()),
                ('last_joined', models.DateTimeField()),
                ('is_admin', models.BooleanField()),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('is_superadmin', models.BooleanField()),
            ],
            options={
                'db_table': 'accounts_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('activo', models.FloatField()),
                ('usermail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('rut_empresa', models.CharField(blank=True, max_length=10, null=True)),
                ('giro', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('numero_folio', models.IntegerField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=300)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('folio', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('total', models.IntegerField()),
                ('nulo', models.FloatField()),
                ('descuento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_emp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('activo', models.FloatField()),
                ('usermail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'grupo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('enuso', models.FloatField()),
            ],
            options={
                'db_table': 'medio_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedidoProducto',
            fields=[
                ('folio_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('recibido', models.FloatField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_pedido_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_corto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('enuso', models.FloatField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_proveedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.FloatField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_sevicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('precio', models.IntegerField()),
                ('enuso', models.FloatField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('pantente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('activo', models.FloatField()),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('servicio_id_sevicio', models.OneToOneField(db_column='servicio_id_sevicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion.servicio')),
            ],
            options={
                'db_table': 'detalle_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id_detalle_servicio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('producto_sku', models.OneToOneField(db_column='producto_sku', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion.producto')),
            ],
            options={
                'db_table': 'detalle_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('sku_fk', models.OneToOneField(db_column='sku_fk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion.producto')),
            ],
            options={
                'db_table': 'orden-producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvProducto',
            fields=[
                ('rut_proveedor', models.OneToOneField(db_column='rut_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion.proveedor')),
            ],
            options={
                'db_table': 'prov-producto',
                'managed': False,
            },
        ),
    ]
