# Generated by Django 4.0.1 on 2022-04-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountsAccount',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.RemoveField(
            model_name='detalledocumento',
            name='servicio_id_sevicio',
        ),
        migrations.RemoveField(
            model_name='detalleservicio',
            name='producto_sku',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='GrupoProducto',
        ),
        migrations.DeleteModel(
            name='MedioPago',
        ),
        migrations.DeleteModel(
            name='OrdenPedidoProducto',
        ),
        migrations.RemoveField(
            model_name='ordenproducto',
            name='sku_fk',
        ),
        migrations.RemoveField(
            model_name='provproducto',
            name='rut_proveedor',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
        migrations.DeleteModel(
            name='TipoEmpleado',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.DeleteModel(
            name='DetalleDocumento',
        ),
        migrations.DeleteModel(
            name='DetalleServicio',
        ),
        migrations.DeleteModel(
            name='OrdenProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='ProvProducto',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
