alter session set "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER C##PY_TALLER IDENTIFIED BY "TMSEadmin"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER C##PY_TALLER QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO C##PY_TALLER ;
GRANT "RESOURCE" TO C##PY_TALLER ;
ALTER USER C##PY_TALLER DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
commit;

