# Generated by Django 4.0.3 on 2022-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is Coach'),
        ),
    ]
