# Generated by Django 4.0.3 on 2022-04-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin_per',
            field=models.BooleanField(default=False, verbose_name='Is Admin Per'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is Client'),
        ),
    ]
