# Generated by Django 4.0.3 on 2022-04-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_admin_per_alter_account_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin_per',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_client',
        ),
    ]
