# Generated by Django 4.0.3 on 2022-04-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_is_admin_per_remove_account_is_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='user_admin',
        ),
    ]
