# Generated by Django 4.0.3 on 2022-04-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_staff_account_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_admin',
            new_name='is_staff',
        ),
    ]
