# Generated by Django 4.0.3 on 2022-04-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('run', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('rut_emp', models.CharField(max_length=10)),
                ('giro', models.CharField(max_length=50)),
                ('razon', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
