# Generated by Django 4.0.1 on 2022-04-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_cliente_last_login_remove_cliente_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
